steps:
  - id: package
    name: 'grc.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      # - '${_IMAGE_NAME}:${_VERSION}'
      # - '-t'
      - '${_IMAGE_NAME}:latest'
      - '.'

images: ['${_IMAGE_NAME}']

substitutions:
  _DEFAULT_REGION: us-central1
  _ARTIFACT_REPO: kys
  _IMAGE_NAME: ${_DEFAULT_REGION}-docker.pkg.dev/know-your-sign/${_ARTIFACT_REPO}/kys-api

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
